spring:
  profiles:
    active: a

eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务

---
spring:
  profiles: a

server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://www.qike.com:9002/eureka,http://www.qike.com:9003/eureka
---
spring:
  profiles: b

server:
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: http://www.qike.com:9001/eureka,http://www.qike.com:9003/eureka

---
spring:
  profiles: c

server:
  port: 9003

eureka:
  client:
    service-url:
      defaultZone: http://www.qike.com:9001/eureka,http://www.qike.com:9002/eureka
