spring:
  profiles:
    active: a

eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/        #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。

---
spring:
  profiles: a

server:
  port: 9001

---
spring:
  profiles: b

server:
  port: 9002

---
spring:
  profiles: c

server:
  port: 9003
